<?php
/**
 * Template for filter items block
 *
 * @see Mage_Catalog_Block_Layer_Filter
 */
?>

<ol>
<?php foreach ($this->getItems() as $_item): ?>
    <li>
        <?php if ($_item->getCount() > 0): 
        $query = array(
            $_item->getFilter()->getRequestVar()=>$_item->getValue(),
            Mage::getBlockSingleton('page/html_pager')->getPageVarName() => null 
        );
		
		?>
			<a href="<?php echo $this->urlEscape($this->helper('vc_priceslider')->getItemUrl($query)) ;?>" onclick="return PriceRange.getContent(this, '<?php echo $this->helper('vc_priceslider')->getItemQuery($query);?>');">			
                <?php echo $_item->getLabel() ?>
                <?php if ($this->shouldDisplayProductCount()): ?>
                <span class="count">(<?php echo $_item->getCount() ?>)</span>
                <?php endif; ?>
            </a>
        <?php else: ?>
            <span>
                <?php echo $_item->getLabel(); ?>
                <?php if ($this->shouldDisplayProductCount()): ?>
                    <span class="count">(<?php echo $_item->getCount() ?>)</span>
                <?php endif; ?>
            </span>
        <?php endif; ?>
    </li>
<?php endforeach ?>
</ol>
