<?php
/**
 * Category layered navigation
 *
 * @see Mage_Catalog_Block_Layer_View
 */
?>
<?php if($this->canShowBlock()): ?>
<div class="block block-layered-nav<?php if (!$this->getLayer()->getState()->getFilters()): ?> block-layered-nav--no-filters<?php endif; ?>">
    <div class="block-title">
        <strong><span><?php echo $this->__('Shop By') ?></span></strong>
    </div>
    <div class="block-content toggle-content">
        <?php echo $this->getStateHtml() ?>
        <?php if ($this->getLayer()->getState()->getFilters()): ?>
            <div class="actions"><a href="<?php echo $this->helper('vc_priceslider')->getClearedUrl() ?>" onclick="return PriceRange.getContent(this, '');"><?php echo $this->__('Clear All') ?></a></div>
        <?php endif; ?>
        <?php //if($this->canShowOptions()): ?>
            <p class="block-subtitle block-subtitle--filter"><?php echo $this->__('Filter') ?></p>
            <dl id="narrow-by-list">
                <?php $_filters = $this->getFilters() ?>
                <?php foreach ($_filters as $_filter): 
				?>
                <?php 
				if($_filter->getItemsCount() || strpos(strtolower($_filter->getFilterModelName()), 'price') > 0): 
				?>
                    <dt><?php echo $this->__($_filter->getName()) ?></dt>
                    <dd><?php echo $_filter->getHtml() ?></dd>
                <?php endif; ?>
                <?php endforeach; ?>
            </dl>
        <?php //endif; ?>
		<script type="text/javascript">decorateDataList('narrow-by-list')</script>
    </div>
</div>
<?php endif; ?>
